student_information=input("Enter The Club Name : ")

student_information.upper()
student_information.lower()
student_information.title()
student_information.replace("value","value")
student_information.find("word")
student_information.count("value")
student_information.startswith("value")
student_information.endswith("value")
student_information.split()
student_information.strip()

club_activities=("Teaching","Games","Quiz","Coading","Learning")
print(club_activities[0])
print(club_activities[4])
print(club_activities[0:4])
print(club_activities.count("Games"))
print(club_activities.index("Quiz"))

club_members=["Abhi","Blessin","Sidharth","Jijo","Sajan","Nikil","Abhinand"]
club_members.append("Aruna")
club_members.extend(["lekshmi","Gowry"])
club_members.remove("Abhi")
club_members.remove("Gowry")
club_members.sort()
club_members.reverse()
club_members.index("Blessin")
club_members.count("Abhinand")
print(club_members)

club_event_participation={"Abhi","Blessin","Sidharth","Jijo"}
club={"Gowry","Lekshmi","Aruna","Blessin"}
club_event_participation.add("Nikhil")
club_event_participation.remove("Abhi")
club_event_participation.discard("Abhi")
print(club_event_participation.union(club))
print(club_event_participation.intersection(club))
print(club_event_participation.difference(club))
print(club_event_participation.symmetric_difference(club))
